# -*- coding: utf-8 -*-
"""oop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-KJRFVqMDuKlqZtMMkMxj2QnDkyaENl
"""

# -*- coding: utf-8 -*-
"""loan_inference_model.py

Automatically generated for loan prediction model inference.
"""

import pickle
import pandas as pd

class LoanApprovalModel:
    def __init__(self, model_path='model.pkl'):
        # Memuat model dan encoder yang telah disimpan sebagai dictionary
        with open(model_path, 'rb') as f:
            data = pickle.load(f)
            self.model = data['model']
            self.encoders = data['encoders']

    def predict(self, input_data: dict):
        df = pd.DataFrame([input_data])

        # Lakukan encoding untuk kolom-kolom kategorikal
        for col, encoder in self.encoders.items():
            if col in df.columns:
                try:
                    df[col] = encoder.transform(df[col])
                except Exception as e:
                    raise ValueError(f"Encoding gagal di kolom '{col}': {e}")

        # Melakukan prediksi
        prediction = self.model.predict(df)[0]
        return prediction

